apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rabbitmq.name" . }}
    helm.sh/chart: {{ include "rabbitmq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  plugins: |
    [
{{- range $plugin := .Values.plugins }}
      {{ $plugin }},
{{- end }}
      rabbitmq_management,
      rabbitmq_peer_discovery_k8s
    ].
  rabbitmq.conf: |
    cluster_formation.peer_discovery_backend  = rabbit_peer_discovery_k8s
    cluster_formation.k8s.host = kubernetes.default
    cluster_formation.k8s.address_type = {{ if .Values.statefulset }}hostname{{ else }}ip{{end}}
    management.load_definitions = /etc/definitions/definitions.json
{{- range $key, $value := .Values.rabbitmq_config }}
    {{ $key }}: {{ $value }}
{{- end }}
