apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rabbitmq.name" . }}
    helm.sh/chart: {{ include "rabbitmq.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- $mq_password := .Values.rabbitmqPassword | default (randAlphaNum 24 | nospace) -}}
  {{- $_ := set .Values "rabbitmqPassword" $mq_password }}
  {{- $mng_password := .Values.managementPassword | default (randAlphaNum 24 | nospace) -}}
  {{- $_ := set .Values "managementPassword" $mng_password }}
  rabbitmq-username: {{ .Values.rabbitmqUsername | b64enc | quote }}
  rabbitmq-password: {{ .Values.rabbitmqPassword | b64enc | quote }}
  management-password: {{ .Values.managementPassword | b64enc | quote }}
  rabbitmq-erlang-cookie: {{ .Values.rabbitmqErlangCookie | default (randAlphaNum 32) | b64enc | quote }}
  definitions.json: {{ include "rabbitmq.definitions" . | b64enc | quote }}
